# Generated by Django 5.0.1 on 2024-01-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isImportant',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
