# Generated by Django 5.0.1 on 2024-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tasks', '0003_task_isimportant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(default=1, to='categories.category'),
        ),
    ]
